### ISSUE TITLE
after update it does not work

### ISSUE THREAD

**Issue by rferrari81** [fgl82/simplemenu#87] opened 2020-05-21 19:21 UTC
hello I have an rg350m, after updating to version 6 of simplemenu it doesn't start anymore

**Comment by fgl82** [comment] 2020-05-25 04:34
Hello, can you describe the issue in more detail?
Steps you took, especially, one by one.
Thanks.

**Comment by rferrari81** [comment] 2020-05-25 04:53
I managed to get it started by completely formatting the SD card and putting the firmware back.  the problem is that very often crashes when I press the L or R keys. is there a way to delete all the simplemenu settings so as to restart it clean?

**Comment by fgl82** [comment] 2020-05-25 12:21
The way to do that is deleting the /home/.simplemenu folder, although if it crashes I'm not sure that will help.

I don't own an rg350m so I'm not sure what can be happening but I'm releasing a new version later today, maybe that one will work better for you.

**Comment by osoblanco32** [comment] 2020-05-25 15:03
I have also had trouble with the rg350m... after copying the opk and running SM once, the new files have not been created?

**Comment by rferrari81** [comment] 2020-05-25 15:23
yes, he created them for me but sometimes crashes

**Comment by fgl82** [comment] 2020-05-25 23:34
6.1 is out, try that one please

**Comment by osoblanco32** [comment] 2020-05-26 07:53
6.1 wont launch, sorry

**Comment by fgl82** [comment] 2020-05-26 14:59
Other people are using it on the rg350m and I don't have one myself so it's hard for me to o ow what could be wrong in your case. If you enable logging in co config.ini and paste it here we can try to see what's wrong

**Comment by osoblanco32** [comment] 2020-05-26 15:36
I assume I need the simplemenu folder to be created to find the config.ini file?
I tried 6.1 again and got the same result and then tried 6.0 again and that wont launch either now so I think there must be some legacy files being stored somewhere - any ideas? hidden files are turned on but I wonder if the device needs to give full permissions maybe? thanks for your help on this

**Comment by fgl82** [comment] 2020-05-26 15:51
If the .simplemenu folder is not even being created, something else is wrong and you cant enable logging.

I'm not sure what could be happening, unless you are not seeing the old .simplemenu folder and it's still there.

I'd suggest going to any of the existing rg350 communities like reddit or discord so you can ask around and see if more people can help you.

**Comment by fgl82** [comment] 2020-05-26 15:52
Just in case, see that I'm.talking about a .simplemenu folder, with a dot, not just "simplemenu"

**Comment by osoblanco32** [comment] 2020-05-26 16:06
yeah, that's correct. nothing gets created anywhere even when v6.0 did launch the other day. weird but I'll try the forums. thanks again for trying!

**Comment by rferrari81** [comment] 2020-05-26 17:08
to me with rg350m now it works, the problem was in the configuration files of the emulators. Some group names were wrong because they have changed in the new version. By fixing this, it now works perfectly.

**Comment by fgl82** [comment] 2020-05-26 22:13
@osoblanco32 please check Ferrari's reply

**Comment by rferrari81** [comment] 2020-05-26 22:25
how do i get FBA games to start?  I enter the FBA app but I have to start it from the list

**Comment by fgl82** [comment] 2020-05-27 00:28
Please dont use the same issue for non relatwd questions. There's an FBA that runs games from my menu and one that doesn't. Seems you have the one that doesn't.

**Comment by fgl82** [comment] 2020-05-27 18:08
Since you confirmed it starts now, I'll close this

**Closed by fgl82** 2020-05-27 18:08 UTC
