### ISSUE TITLE
Not Launching, no .simplemenu folder

### ISSUE THREAD

**Issue by tperry82** [fgl82/simplemenu#52] opened 2020-02-17 13:51 UTC
Did everything for PocketGo V2  as instructed on this page, but when I launch SimpleMenu, it says it launches for half a sec and then goes back to the default menu. Also, there is no .simplemenu folder in the described location. Can somebody help me out, please? Much apreciated!

**Comment by fgl82** [comment] 2020-02-17 19:15
@fperry82, try copying the files directly to the sd, instead of through ftp, please.

**Comment by fgl82** [comment] 2020-02-17 19:16
I'm closing this as it's not a bug, probably either a config issue or a copying issue, feel free to reach out to me on discord by PM so I can help you there.

Thanks.

**Closed** 2020-02-17 19:16 UTC

**Comment by tperry82** [comment] 2020-02-18 08:28
Ok, I understand. Not really a DEV so...Discord says I need 4 numbers to be able to contact you

**Comment by fgl82** [comment] 2020-02-18 15:55
@tperry82 I have no idea what that means... people PM me all the time there

**Comment by fgl82** [comment] 2020-02-18 15:59
Ah, I see, it's FGL82#0700
