### ISSUE TITLE
Execution problem in OPK

### ISSUE THREAD

**Issue by eduardofilo** [fgl82/simplemenu#61] opened 2020-02-22 20:46 UTC
Hi. I have tried to use OPK installation of versions 3.2 and 3.3 and I have not succeeded. I have 'unsquashed' the OPK and added execution permission to `invoker.dge` and `simplemenu` files, then 'resquashed' and the program starts working.

Thanks for your program by the way.

**Comment by fgl82** [comment] 2020-02-28 17:52
Hey @eduardofilo, or Hola, since I think you speak Spanish?

Thanks for the info, I will try to make sure the next release is right.

Would you please send me your resquashed OPKs?

I will close this as it's not a bug in the code, but will add a note to the release files later.

**Comment by fgl82** [comment] 2020-02-28 17:53
Not a bug in the code

**Closed** 2020-02-28 17:52 UTC

**Comment by fgl82** [comment] 2020-02-28 17:58
@eduardofilo esto es genial!
http://apuntes.eduardofilo.es/2020-01-25-rg350_simplemenu.html

**Comment by eduardofilo** [comment] 2020-02-28 23:26
I'm glad you like it. As probably you have seen, the OPK with fixed permissions is linked to that page:
http://apuntes.eduardofilo.es/files/posts/SimpleMenu-RG-350_fixed.opk
