### ISSUE TITLE
Default launcher option doesn't work on pocket go 2

### ISSUE THREAD

**Issue by phekda** [fgl82/simplemenu#81] opened 2020-05-07 10:10 UTC
The option Default launcher doesn't work on the pocket go 2. When I choose YES it will automatically go back to NO after shutdown or reboot. It always fall back to gmenu2x. I am using the latest Rogue FW 1.0.5 on PG2.

**Comment by fgl82** [comment] 2020-05-08 17:04
First report I get of this. Did you rename your opk by any chance?

**Comment by phekda** [comment] 2020-05-09 17:28
No i didn't rename the opk... I just did a fresh installation of the firmware and checked everything. Still it won't work. 
Simplemenu never starts after boot :-( 
I would love to see this option to work as i really prefer your frontend menu system then any other existing menu.

**Comment by fgl82** [comment] 2020-05-10 00:18
Do you have rogue or the default firmware?

**Comment by fgl82** [comment] 2020-05-10 00:19
Ah, rogue 1.0.5, sorry, missed that, well, I'll take a look

**Comment by phekda** [comment] 2020-05-10 07:04
> Ah, rogue 1.0.5, sorry, missed that, well, I'll take a look

Rogue 1.0.6 right now actually. Thank you that is great news!

**Comment by urby66** [comment] 2020-05-10 07:22
Hello, 
I can confirm, the auto-start feature is not working with Rogue 1.06, clean install. 
If I copy the  frontend_start into the sbin folder, the program can start automatically, but the shutdown option is still missing from the settings screen. This case the settings screen looks like similar when program is started manually from gmenu2x, and the default launcher option is shows no.

**Comment by fgl82** [comment] 2020-05-17 18:54
@phekda, @urby66 this si fixed on 60. could you please retry and close the bug if it works?

**Comment by phekda** [comment] 2020-05-18 14:15
I am sorry to tell  you that it still doesn't work. Same behaviour as before. Soon I will have a rg350m and then simplemenu will work as it should ;)

**Comment by fgl82** [comment] 2020-05-18 15:29
@phekda I will double check the code and if it still looks wrong, will put out a minor update today

**Comment by fgl82** [comment] 2020-05-18 15:35
@phekda I've just looked at the code and found the issue, will put out an update tonight

**Comment by phekda** [comment] 2020-05-18 19:48
Ok great! I'll test it tomorrow

**Comment by egeon44** [comment] 2020-05-20 07:12
Hi, Simplemenu is the best frontend on pocket go 2. Do you know when we could have a release with this bug corrected ? Thx for your work !

**Comment by phekda** [comment] 2020-05-20 10:16
> Ok great! I'll test it tomorrow

I don't know if you updated the program but it is still not working.

**Comment by fgl82** [comment] 2020-05-25 17:31
No, there's no new release under releases, right? So not updated yet

**Comment by fgl82** [comment] 2020-05-25 23:33
Please check now

**Comment by egeon44** [comment] 2020-05-26 06:39
Hi, on my new pocket go 3.12.0-dingux, with the last build, it doesn't start at all.

**Comment by egeon44** [comment] 2020-05-26 06:46
the log : 
... INFO | Loading sections
... INFO | GAMES
ERROR | Nice, a critical error!!!

**Comment by fgl82** [comment] 2020-05-26 14:57
Please open a new bug for this

**Comment by fgl82** [comment] 2020-05-27 18:09
@phekda can you conform if it's fixed in pg2?

**Comment by egeon44** [comment] 2020-05-28 10:09
with simplemenu opk RG-350 6.1 on CFW 1.0.8 for PG2 : boot & shutdown work

**Comment by phekda** [comment] 2020-06-01 11:15
Sorry @fgl82 I didn't made time yet to test on pg2 but i wil certainly do in the following days.
However I've found a small error in the /local/sbin/frontend_start file made by the rg350m version of your program. 
Corrected it should look like this:

if [ -f /media/data/SimpleMenu/simplemenu ]; then
    cd /media/data/SimpleMenu
    ./simplemenu
elif [ -f /media/data/apps/SimpleMenu-RG-350.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/data/apps/SimpleMenu-RG-350m.opk
elif [ -f /media/sdcard/apps/SimpleMenu-RG-350.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/sdcard/apps/SimpleMenu-RG-350m.opk
elif [ -f /media/data/apps/SimpleMenu-RG-350m.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/data/apps/SimpleMenu-RG-350.opk
elif [ -f /media/sdcard/apps/SimpleMenu-RG-350m.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/sdcard/apps/SimpleMenu-RG-350.opk
elif [ -f /media/data/apps/SimpleMenu-PG2.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/data/apps/SimpleMenu-PG2.opk
elif [ -f /media/data/sdcard/SimpleMenu-PG2.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/sdcard/apps/SimpleMenu-PG2.opk
elif [ -f /media/data/apps/gmenunx.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/data/apps/gmenunx.opk
else
    /usr/bin/gmenu2x
fi

**Comment by fgl82** [comment] 2020-12-06 22:33
@phekda , I'm assuming this is fixed now, you can email me if it isn't.

**Closed** 2020-12-06 22:33 UTC
