### ISSUE TITLE
Battery indicator?

### ISSUE THREAD

**Issue by AurelioB** [fgl82/simplemenu#75] opened 2020-04-25 02:39 UTC
Hi, really loving this launcher. The only real thing I'm missing from default one is a battery indicator. I see in the source code that there's code for writing battery level to a footer, but the code is commented. Is this a discarded feature? Or is the code not ready yet?
Thanks!

**Comment by fgl82** [comment] 2020-04-29 03:15
I scraped that idea a long time ago, we have the console led to show when it's dying, I felt it took away from the aesthetics, I won't be adding it in the near future.

Maybe when I run out of other things I want to do :)

I'm closing this for now since it's not a bug.

Thanks for the interest.

**Closed** 2020-04-29 03:15 UTC
