### ISSUE TITLE
Version 5.5 not working for PG2

### ISSUE THREAD

**Issue by wermelinger** [fgl82/simplemenu#76] opened 2020-04-25 12:03 UTC
First of all, I love the SimpleMenu - it really makes using my PG2 a great experience!
The version 5.5 though was not working for my PG2. It closed every time I tried to start a game. I tried the following approaches:

- Install 5.5, let SimpleMenu generate the home folder, then I copied my section_group as usual
- Install 5.5, adapt the section_group for a system manually 
- Install 5.5, copy favorites.sav, try to start a game from the favorite-list

Keep up the good work

**Comment by fgl82** [comment] 2020-04-29 03:13
Did you try deleting last_state.sav after copying your own section group?

**Comment by wermelinger** [comment] 2020-04-29 07:46
Yes, I tried that. I also tried to delete .simplemenu folder, let SimpleMenu regenerate it and adapt the section group to match my sd-card structure. Same result. I have also the same behavior for the Games & Apps (without changing any section group).
When I go back to v 5.3, everything works fine.
Is there any log file I could provide?

**Comment by GeekGuyMJ** [comment] 2020-04-29 20:56
I have the same issue with my PG2. I had to go back to v. 5.3 to get it working.

**Comment by phekda** [comment] 2020-05-02 09:34
Same problem here... I am using Rogue FW 1.4 and Simple Menu 5.5 is quiting when trying to launch an emulator.

**Comment by chadzero5** [comment] 2020-05-02 10:16
I get the same issue. Running a PG2, fresh firmware install with Rogue 1.0.5. 
If I run it from the default menu I get a black screen for 1 second then it kicks me back. If I open it with the Explorer I get an error log for a simple second. Manage to capture the error here:

https://imgur.com/a/C5jP0cn

**Comment by chadzero5** [comment] 2020-05-02 10:17
![VideoCapture_20200502-200714](https://user-images.githubusercontent.com/60199255/80861433-e2c6c980-8cb1-11ea-88f3-c89b06825ef2.jpg)

**Comment by fgl82** [comment] 2020-05-02 19:11
Hi! Please use 5.6 now, the opk for 5.5 was bad for the PG2. Sorry about that :)

**Comment by fgl82** [comment] 2020-05-02 19:11
@wermelinger and @chadzero5

**Comment by chadzero5** [comment] 2020-05-03 02:21
Hi @fgl82 , still get the same issue :( When I run it once, I get a black screen. Had a look to see if it made a folder called /home/.simplemenu but nothing there.

**Comment by fgl82** [comment] 2020-05-03 03:36
Are you running stock firmware?

**Comment by fgl82** [comment] 2020-05-03 03:37
It doesn't make much sense that it cant open the opk otherwise, as I tested it on my rg350 )the pg2 opk works there as well) and verified it worked

**Comment by chadzero5** [comment] 2020-05-03 05:06
I'm running CFW Rogue 1.0.5. Does this currently just work with stock firmware?

**Comment by fgl82** [comment] 2020-05-03 05:43
No, but it does work in rogue, so your case is pretty strange

**Comment by fgl82** [comment] 2020-05-03 05:44
Did you copy the opk to the sd card directly or through ftp?

**Comment by chadzero5** [comment] 2020-05-03 06:06
So I've been using FTP this entire time - I just tried copying to SD card directly, same result (this was with 5.6.1)

**Comment by phekda** [comment] 2020-05-03 10:05
I can confirm that i have the same issue as chadzero5. I am running 1.0.5 rogue fw and using your latest opk for pg2. Your latest 5.6 opk won't even start. I will try downgrading because 5.3 was working earlier.

**Comment by fgl82** [comment] 2020-05-03 13:11
Aren't there more recent versions of rogue? I do t use rogue or have a pocket go 2, so I won't be able to fix any issues inked to rogue, sadly

**Comment by fgl82** [comment] 2020-05-03 13:12
Other people with rogue are running it fine as far as I know, so maybe ask around...

**Comment by fgl82** [comment] 2020-05-03 13:17
Oh, I see 1.0.5 is very recent, I'm  blaming Rogue then :P

**Comment by fgl82** [comment] 2020-05-03 13:37
OK, I think I know what's wrong with the PG2 OPK, can you please try to doe load 5.6.1 again and see if it works now?

**Comment by Ninoh-FOX** [comment] 2020-05-03 14:12
work fine now

**Comment by fgl82** [comment] 2020-05-03 14:16
Ninoh here helped me see I was including a lib that the pg2 doesn't have

**Comment by fgl82** [comment] 2020-05-03 17:52
@phekda, @wermelinger, @GeekGuyMJ

**Comment by phekda** [comment] 2020-05-03 18:46
Yes... You did it. It is working like a charm now! Thank you so much fgl82 and great to see the teamwork between you and Ninoh-FOX. Your menu is simply amazing.

**Comment by fgl82** [comment] 2020-05-03 18:53
Thanks for replying! Closing the issue then

**Closed by fgl82** 2020-05-03 18:53 UTC

**Comment by wermelinger** [comment] 2020-05-03 19:58
I can confirm 5.6.1 is working again! Running 1.0.4 rogue on PG2.
Great work!

**Comment by fgl82** [comment] 2020-05-03 21:33
Thanks for confirming!

**Comment by chadzero5** [comment] 2020-05-03 22:55
Can confirm it now works in Rogue 1.0.5! Thanks so much @fgl82
