### ISSUE TITLE
Changing layout on newest version?

### ISSUE THREAD

**Issue by TmDobbin** [fgl82/simplemenu#149] opened 2021-01-17 18:49 UTC
On the newest version, is it no longer possible _at all_ to change the layout to something like drunken monkey? Or is it only changeable in a config file? (Side note - making the tmp file seems to crash when it gets to my PS1 collection, with about 36 games in it. Is the collection too large?)

**Comment by westoncampbell** [comment] 2021-01-19 14:03
I experienced the same crashing issue with PlayStation.

I believe my issue is from having each PS1 disk image in separate folders.

Could you try putting your .bin & .cue files in the root PS1 folder without having a different folder for each game? This worked for me, and I would like to see if it works for you too.

Would like to find out if that is actually the cause of the issue.

**Comment by TmDobbin** [comment] 2021-01-20 15:09
> I experienced the same crashing issue with PlayStation.
> 
> I believe my issue is from having each PS1 disk image in separate folders.
> 
> Could you try putting your .bin & .cue files in the root PS1 folder without having a different folder for each game? This worked for me, and I would like to see if it works for you too.
> 
> Would like to find out if that is actually the cause of the issue.

Yep, that seems to have fixed the crashing issue. Not only are my bin & cue files in their own folders but multi-disc games are also nested (i.e. PS1/Final Fantasy VII/Disc 1/,  PS1/Final Fantasy VII/Disc 2/ etc) After dropping all the files into one folder it doesn't crash anymore. Kind of a shame, hopefully this can be fixed in a future release. Also with the removed ability to change to a different layout, I'll be sticking with a previous release for now. Thanks for your help!

**Comment by fgl82** [comment] 2021-03-07 23:53
@TmDobbin this should be fixed, please let me know if 6.9 works fine for you

**Comment by fgl82** [comment] 2021-03-29 04:44
This is fixed

**Closed** 2021-03-29 04:44 UTC
